on:
  push:
    branches: [ master ]
  
name: Deploy via FTP
jobs:
  DeployFTP:        
    name: Deploy via FTP	
    runs-on: ubuntu-latest	
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    
    - name: List output files
      run: ls
      
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ftp.ladislavprix.cz
        ftp-username: root.ladislavprix.cz
        ftp-password: ${{ secrets.FTP_PASSWORD }}
